export const ADD_ONE = "ADD_ONE";
export const MINUS_ONE = "MINUS_ONE";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REQUEST_SENT = "REQUEST_SENT";
export const REQUEST_FINISHED = "REQUEST_FINISHED";
export const NOTIFY_USER = "NOTIFY_USER";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
export const UPDATE_USER = "UPDATE_USER";

// Pet actions
export const LOAD_PETS = "LOAD_PETS";
export const ADDED_PET = "ADDED_PET";
export const UPDATED_PET = "UPDATED_PET";
export const DELETED_PET = "DELETED_PET";
export const SELECT_PET = "SELECT_PET";

// Vaccionation actions
export const LOAD_VACCINATIONS = "LOAD_VACCINATIONS";
export const ADDED_VACCINATION = "ADDED_VACCINATION";
export const UPDATED_VACCINATION = "UPDATED_VACCINATION";
export const DELETED_VACCINATION = "DELETED_VACCINATION";
export const SELECT_VACCINATION = "SELECT_VACCINATION";
export const LOAD_MORE_VACCINATIONS = "LOAD_MORE_VACCINATIONS";

// Procedure actions
export const LOAD_PROCEDURES = "LOAD_PROCEDURES";
export const ADDED_PROCEDURE = "ADDED_PROCEDURE";
export const UPDATED_PROCEDURE = "UPDATED_PROCEDURE";
export const DELETED_PROCEDURE = "DELETED_PROCEDURE";
export const SELECT_PROCEDURE = "SELECT_PROCEDURE";

// Grooming actions
export const LOAD_GROOMING = "LOAD_GROOMING";
export const ADDED_GROOMING = "ADDED_GROOMING";
export const UPDATED_GROOMING = "UPDATED_GROOMING";
export const DELETED_GROOMING = "DELETED_GROOMING";
export const SELECT_GROOMING = "SELECT_GROOMING";

// Reminder actions
export const LOAD_REMINDERS = "LOAD_REMINDERS";
export const ADDED_REMINDER = "ADDED_REMINDER";
export const UPDATED_REMINDER = "UPDATED_REMINDER";
export const DELETED_REMINDER = "DELETED_REMINDER";
export const SELECT_REMINDER = "SELECT_REMINDER";

// Timeline actions
export const LOAD_TIMELINE = "LOAD_TIMELINE";
